# Generated by Django 3.2.9 on 2023-01-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_chrome_extension_chrome_extension_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chrome_extension_update',
            name='xml_file',
            field=models.FileField(blank=True, upload_to='chrome_extension_updates'),
        ),
    ]
