# Generated by Django 3.2.6 on 2022-04-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_texteditor_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
