# Generated by Django 3.2.6 on 2022-04-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
