# Generated by Django 3.2.6 on 2022-04-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_workexperience_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='total_time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
