# Generated by Django 3.2.6 on 2022-04-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_aboutme_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='image',
        ),
    ]
