# Generated by Django 3.2.6 on 2022-04-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_aboutme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
