# Generated by Django 3.2.9 on 2022-07-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='profile_pics')),
            ],
        ),
    ]
