# Generated by Django 3.2.9 on 2022-07-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_websiteicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='id',
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='content',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
