# Generated by Django 3.2.9 on 2022-07-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20220713_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
