# Generated by Django 3.2.9 on 2022-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_workexperience_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='title',
            field=models.CharField(default='About Me', max_length=100),
        ),
    ]
