# Generated by Django 3.2.9 on 2022-07-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_aboutme_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certification',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='email',
            field=models.CharField(default='email@email.com', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='location',
            field=models.CharField(default='495 Your address here', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='phone',
            field=models.CharField(default='Phone Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='title',
            field=models.CharField(default='Career Title', max_length=100),
        ),
    ]
