# Generated by Django 3.2.9 on 2022-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20220719_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='certification_pics'),
        ),
    ]
