# Generated by Django 3.2.9 on 2022-07-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_certification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, upload_to='certification_pics'),
        ),
    ]
