# Generated by Django 3.2.9 on 2022-07-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_certification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
