# Generated by Django 3.2.9 on 2022-07-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_workexperience_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
