# Generated by Django 3.2.9 on 2022-07-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20220722_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='work_experience',
            field=models.BooleanField(default=True),
        ),
    ]
