# Generated by Django 3.2.9 on 2022-08-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20220722_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='github_handle',
            field=models.CharField(default='mygithubhandle', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='linkedin_url',
            field=models.CharField(default='https://linkedin.com/yourlinkedin', max_length=300),
        ),
    ]
