# Generated by Django 3.2.9 on 2023-01-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_skill_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(blank=True, upload_to='skills_pics'),
        ),
    ]
