# Generated by Django 3.2.9 on 2023-07-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='mastadon_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
